type CommandResponse {
  "Response code"
  code: Int
  "Response message"
  message: String
}

type msnamecamelmsentitypascal {
  "msentitypascal ID"
  id: ID!
  "User general info"
  generalInfo: msentitypascalGeneralInfo
  "msentitypascal state"
  state: Boolean!
  "Creation timestamp"
  creationTimestamp: BigInt!
  "Creator user"
  creatorUser: String!
  "Modification timestamp"
  modificationTimestamp: BigInt!
  "Modifier user"
  modifierUser: String!
  "Business ID"
  businessId: String!
}

type msentitypascalGeneralInfo {
  "msentitypascal name"
  name: String!,
  "msentitypascal description"
  description: String!
}

input FilterInput {
  "ID of the business"
  businessId: String
  "State"
  state: Boolean
  "Creator user"
  creatorUser: String
  "modifier user"
  modifierUser: String
  "get data created after indicated timestamp"
  creationTimestamp: BigInt
}

input PaginationInput {
  "Page"
  page: Int!
  "Count"
  count: Int!
  "Sort, default: ASC"
  sort: Int
}

input msentitypascalInput {
  "msentitypascal general info"
  generalInfo: msentitypascalGeneralInfoInput!
  "msentitypascal status"
  state: Boolean!
  "Business ID"
  businessId: String!
}

input msentitypascalGeneralInfoInput {
  "msentitypascal name"
  name: String!,
  "msentitypascal description"
  description: String!
}

type Query {
  "Get msentitiespascal filtered "
  msnamecamelmsentitiespascal(filterInput: FilterInput!, paginationInput: PaginationInput!): [msnamecamelmsentitypascal]
  "Get the amount of msentitiespascal filtered "
  msnamecamelmsentitiespascalSize(filterInput: FilterInput!): Int!
  "Get msentitypascal by its id"
  msnamecamelmsentitypascal(id: String!): msnamecamelmsentitypascal
}

type Mutation {
  "Create a new msentitypascal"
  msnamecamelCreatemsentitypascal(input: msentitypascalInput!): CommandResponse
  "Update the msentitypascal generalInfo"
  msnamecamelUpdatemsentitypascalGeneralInfo(id:ID!, input: msentitypascalGeneralInfoInput!): CommandResponse
  "Update the msentitypascal state"
  msnamecamelUpdatemsentitypascalState(id: ID!, newState: Boolean!): CommandResponse
}

type Subscription {
  "This events is triggered when a msentitypascal is created or updated"
  msnamecamelmsentitypascalUpdatedSubscription: msnamecamelmsentitypascal  
}